### ISSUE TITLE
Selecting local files does not work on Android devices

### ISSUE THREAD

**Issue by suterma** [suterma/replayer-pwa#153]
When clicking the "open file" button, the presented file list is not working properly.

- No audio files are presented
- The files available can not be selected

**Comment by suterma** [comment]
This seems to be related to the "accept" attribute of the file input HTML element. A simpler accept value does work.

**Comment by suterma** [comment]
**TEST:**

On an Android device (FP3, Lenovo Tablet)

- click the "open file" button
- Files of all supported types should be presented: Audio, Video, PDF, Text, ZIP and XML
- selecting the file should load it's content

Test for all the above types

**Comment by wilbert-alberts** [comment]
Works for OnePlus NordCE 5G (EB2103) 
- Pressing open lets user choose between applications that can open files. Mediachooser is one of them and that one now allows to select mp3 (and a lot of others). 

Works on Samsung Galaxy Tab S7 FE
- Actually previous version already worked. After pressing load, the mediachooser provides the options to 'select sounds'. That one (seems to) uses some kind of media catalogue from which I could select mp3 as long as they had been indexed before. The new version seems to provide even more options to retrieve files.

Works for Samsung Galaxy Tab A9 +
- Same as for Tab S7 FE

Chromebooks  (Lenovo flex 5 and Asus CM5500FD) already worked. Pressing load allowed for selecting local files.

**Comment by suterma** [comment]
Thanks @wilbert-alberts for testing this.
